name: Notification

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Notify success
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: 'MedConnect deployed successfully! 🚀'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
